import React, { useEffect, useState } from 'react';
import { CheckCircle2, ExternalLink, Gauge, Globe2, LogOut, MessageSquare, Package, Save, Settings2, ShieldCheck, XCircle } from 'lucide-react';
import { api } from '../lib/api';
import { supabase } from '../lib/supabase';
import { setCurrentUser } from '../lib/store';
interface Props { onNavigate:(path:string)=>void; }
export const AdminDashboardPage: React.FC<Props> = ({onNavigate}) => {
 const [tab,setTab]=useState<'overview'|'requests'|'rates'|'site'>('overview');
 const [requests,setRequests]=useState<any[]>([]); const [rates,setRates]=useState<any[]>([]); const [settings,setSettings]=useState<any>({}); const [shipments,setShipments]=useState<any[]>([]);
 const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 const [rate,setRate]=useState({service:'Express',originCountry:'Nigeria',destCountry:'United States',baseRate:0,perKgRate:0,estDaysMin:1,estDaysMax:3,currency:'USD',active:true});
 const load=async()=>{setBusy(true);setMessage('');try{const [reqs,rs,ss,sh]=await Promise.all([api.adminGuestRequests(),api.adminRates(),api.adminSiteSettings(),api.shipments()]);setRequests(reqs);setRates(rs);setSettings(ss);setShipments(sh);}catch(e){setMessage(e instanceof Error?e.message:'Admin data could not be loaded.')}finally{setBusy(false);}};
 useEffect(()=>{load();},[]);
 const updateRequest=async(id:string,status:'approved'|'declined')=>{const note=window.prompt(status==='approved'?'Approval note':'Reason for decline')||'';setBusy(true);try{await api.adminUpdateGuestRequest(id,status,note);await load();}catch(e){setMessage(e instanceof Error?e.message:'Request update failed.')}finally{setBusy(false);}};
 const saveRate=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await api.adminSaveRate(rate);await load();setMessage('Production rate saved.');}catch(e){setMessage(e instanceof Error?e.message:'Rate could not be saved.')}finally{setBusy(false);}};
 const saveSite=async()=>{setBusy(true);try{await api.adminSaveSiteSettings(settings);setMessage('Homepage settings saved.');}catch(e){setMessage(e instanceof Error?e.message:'Homepage settings could not be saved.')}finally{setBusy(false);}};
 const logout=async()=>{await supabase.auth.signOut();setCurrentUser(null);onNavigate('/login')};
 return <div className="min-h-screen bg-[#f6f9fd] px-4 py-7 sm:px-6 lg:px-8"><div className="mx-auto max-w-[1500px]">
 <div className="rounded-[30px] bg-gradient-to-br from-[#16052a] via-[#35105f] to-[#4D148C] p-6 text-white shadow-2xl sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.14em]"><ShieldCheck className="h-3.5 w-3.5 text-[#ff8a42]"/> Protected administrator console</div><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Website Control Center</h1><p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-white/70">Control guest requests, production shipping rates and the homepage presentation from one admin-only workspace.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>onNavigate('/')} className="rounded-xl bg-white/10 px-4 py-2 text-xs font-black hover:bg-white/15"><ExternalLink className="mr-1 inline h-4 w-4"/> Live site</button><button onClick={logout} className="rounded-xl bg-white px-4 py-2 text-xs font-black text-[#4D148C]"><LogOut className="mr-1 inline h-4 w-4"/> Sign out</button></div></div></div>
 {message&&<div className="mt-4 rounded-xl border border-[#dce4ef] bg-white p-3 text-sm font-bold text-[#33456f]">{message}</div>}
 <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4">{[['Paid pending review',requests.filter(r=>r.status==='paid_pending_review').length,Package],['Approved',requests.filter(r=>r.status==='approved').length,CheckCircle2],['Active rates',rates.filter(r=>r.active!==false).length,Gauge],['Production shipments',shipments.length,Globe2]].map(([label,value,Icon]:any)=><div key={label} className="rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm"><Icon className="h-5 w-5 text-[#4D148C]"/><div className="mt-3 text-2xl font-black text-[#16285e]">{value}</div><div className="mt-1 text-[10px] font-black uppercase tracking-[.12em] text-[#7d89a0]">{label}</div></div>)}</div>
 <div className="mt-6 flex gap-2 overflow-x-auto rounded-2xl border border-[#dfe5ef] bg-white p-2 shadow-sm">{[['overview','Overview'],['requests','Guest requests'],['rates','Shipping rates'],['site','Website settings']].map(([id,label])=><button key={id} onClick={()=>setTab(id as any)} className={'whitespace-nowrap rounded-xl px-4 py-3 text-xs font-black '+(tab===id?'bg-[#4D148C] text-white':'text-[#405074] hover:bg-[#f3f5fa]')}>{label}</button>)}</div>
 {tab==='overview'&&<div className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><div className="rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-[#17285e]">Latest guest requests</h2><div className="mt-4 space-y-3">{requests.slice(0,8).map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#e6eaf1] p-3"><div className="min-w-0 flex-1"><div className="text-xs font-black text-[#26386a]">{r.requestNumber}</div><div className="text-[10px] font-semibold text-[#7b879f]">{r.firstName} {r.lastName} · {r.email}</div></div><span className="rounded-full bg-[#f0e8ff] px-2.5 py-1 text-[10px] font-black text-[#4D148C]">{r.status}</span><button onClick={()=>onNavigate('/communication?request='+r.id)} className="rounded-lg border border-[#dce3ed] p-2 text-[#4D148C]"><MessageSquare className="h-4 w-4"/></button></div>)}{!requests.length&&<div className="py-10 text-center text-sm font-semibold text-[#7b879f]">No guest requests yet.</div>}</div></div><div className="rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-[#17285e]">Admin responsibilities</h2><div className="mt-4 space-y-3">{['Review paid guest requests','Maintain production shipping rates','Control homepage hero copy and photo','Monitor production shipments','Keep customer communication moving'].map((x,i)=><div key={x} className="flex items-center gap-3 rounded-xl bg-[#f7f9fd] p-3"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#f0e8ff] text-xs font-black text-[#4D148C]">{i+1}</span><span className="text-xs font-black text-[#2c3d67]">{x}</span></div>)}</div></div></div>}
 {tab==='requests'&&<div className="mt-5 rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-black text-[#17285e]">Guest request review</h2><span className="text-[10px] font-black uppercase text-[#7b879f]">Payment before review</span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="bg-[#fafbfe] text-[9px] font-black uppercase tracking-wider text-[#8a95ab]"><tr><th className="p-3">Request</th><th className="p-3">Customer</th><th className="p-3">Route</th><th className="p-3">Payment</th><th className="p-3">Status</th><th className="p-3">Control</th></tr></thead><tbody className="divide-y divide-[#edf0f5]">{requests.map(r=><tr key={r.id}><td className="p-3 font-black text-[#26386a]">{r.requestNumber}</td><td className="p-3"><div className="font-bold">{r.firstName} {r.lastName}</div><div className="text-[10px] text-[#7b879f]">{r.email}</div></td><td className="p-3 font-semibold">{r.sender?.city||'—'} → {r.recipient?.city||'—'}</td><td className="p-3 font-black">{r.quotedCost ? (r.currency+' '+Number(r.quotedCost).toFixed(2)) : 'Pending'}</td><td className="p-3 font-bold">{r.status}</td><td className="p-3">{r.status==='paid_pending_review'?<div className="flex gap-2"><button onClick={()=>updateRequest(r.id,'approved')} disabled={busy} className="rounded-lg bg-emerald-600 px-3 py-2 text-[10px] font-black text-white"><CheckCircle2 className="mr-1 inline h-3 w-3"/> Approve</button><button onClick={()=>updateRequest(r.id,'declined')} disabled={busy} className="rounded-lg bg-rose-600 px-3 py-2 text-[10px] font-black text-white"><XCircle className="mr-1 inline h-3 w-3"/> Decline</button></div>:<span className="text-[10px] font-bold text-[#7b879f]">No action</span>}</td></tr>)}</tbody></table></div></div>}
 {tab==='rates'&&<div className="mt-5 grid gap-5 lg:grid-cols-[.72fr_1.28fr]"><form onSubmit={saveRate} className="rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm space-y-3"><h2 className="text-lg font-black text-[#17285e]">Add production rate</h2>{[['service','Service'],['originCountry','Origin country'],['destCountry','Destination country'],['baseRate','Base rate'],['perKgRate','Per kg rate'],['estDaysMin','Min days'],['estDaysMax','Max days']].map(([k,l])=><label key={k} className="block text-[10px] font-black uppercase text-[#66738e]">{l}<input value={(rate as any)[k]} type={['baseRate','perKgRate','estDaysMin','estDaysMax'].includes(k)?'number':'text'} onChange={e=>setRate(v=>({...v,[k]:['baseRate','perKgRate','estDaysMin','estDaysMax'].includes(k)?Number(e.target.value):e.target.value}))} className="mt-1 w-full rounded-xl border border-[#d9e1ed] px-3 py-2.5 text-sm font-bold"/></label>)}<button disabled={busy} className="w-full rounded-xl bg-[#4D148C] py-3 text-sm font-black text-white"><Save className="mr-1 inline h-4 w-4"/> Save rate</button></form><div className="rounded-2xl border border-[#dfe5ef] bg-white p-5 shadow-sm"><h2 className="text-lg font-black text-[#17285e]">Configured rates</h2><div className="mt-4 space-y-2">{rates.map(r=><div key={r.id} className="flex flex-wrap items-center gap-3 rounded-xl border border-[#e6eaf1] p-3"><div className="flex-1"><div className="text-xs font-black">{r.service} · {r.originCountry} → {r.destCountry}</div><div className="text-[10px] font-semibold text-[#7b879f]">{r.currency} {r.baseRate} + {r.perKgRate}/kg · {r.estDaysMin}-{r.estDaysMax} days</div></div><span className={'rounded-full px-2 py-1 text-[9px] font-black '+(r.active!==false?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500')}>{r.active!==false?'ACTIVE':'OFF'}</span></div>)}</div></div></div>}
 {tab==='site'&&<div className="mt-5 rounded-2xl border border-[#dfe5ef] bg-white p-6 shadow-sm"><div className="flex items-center gap-3"><Settings2 className="h-5 w-5 text-[#4D148C]"/><div><h2 className="text-lg font-black text-[#17285e]">Homepage controls</h2><p className="text-xs font-semibold text-[#7b879f]">These values are rendered on the public homepage.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="text-xs font-black">Headline<input value={settings.headline||''} onChange={e=>setSettings((v:any)=>({...v,headline:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d9e1ed] px-3 py-3"/></label><label className="text-xs font-black">Accent<input value={settings.accent||''} onChange={e=>setSettings((v:any)=>({...v,accent:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d9e1ed] px-3 py-3"/></label><label className="md:col-span-2 text-xs font-black">Supporting copy<textarea value={settings.copy||''} onChange={e=>setSettings((v:any)=>({...v,copy:e.target.value}))} className="mt-1.5 min-h-28 w-full rounded-xl border border-[#d9e1ed] px-3 py-3"/></label><label className="md:col-span-2 text-xs font-black">Hero photo URL<input value={settings.heroImage||''} onChange={e=>setSettings((v:any)=>({...v,heroImage:e.target.value}))} className="mt-1.5 w-full rounded-xl border border-[#d9e1ed] px-3 py-3"/></label></div><button onClick={saveSite} disabled={busy} className="mt-5 rounded-xl bg-[#4D148C] px-5 py-3 text-sm font-black text-white"><Save className="mr-1 inline h-4 w-4"/> Save website controls</button></div>}
 </div></div>;
};