import React, { useEffect, useState } from 'react';
import { AlertCircle, ArrowRight, CheckCircle2, Loader2, LogOut, ShieldCheck } from 'lucide-react';
import { Logo } from '../components/common/Logo';
import { supabase } from '../lib/supabase';
import { api } from '../lib/api';
import { setCurrentUser } from '../lib/store';

interface Props { mode:'login'|'register'; onNavigate:(path:string)=>void; }

export const AuthPages:React.FC<Props>=({mode,onNavigate})=>{
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [email,setEmail]=useState<string|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setEmail(data.session?.user.email||null))},[]);
 const finish=async()=>{try{const me=await api.me();const p=me.profile||{};setCurrentUser({id:me.uid,firstName:p.firstName||'',lastName:p.lastName||'',email:me.email,phone:p.phone||'',role:me.admin?'admin':'customer',country:p.country||'',status:p.status||'active',createdAt:p.createdAt||new Date().toISOString()});onNavigate(me.admin?'/admin':'/dashboard')}catch(e){setError(e instanceof Error?e.message:'Account profile could not be loaded.')}};
 const google=async()=>{setBusy(true);setError('');try{const {error:e}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:window.location.origin+'/login'}});if(e)throw e;}catch(e){setError(e instanceof Error?e.message:'Google sign-in could not be started.');setBusy(false)}};
 const logout=async()=>{setBusy(true);await supabase.auth.signOut();setCurrentUser(null);setEmail(null);setBusy(false)};
 return <div className="min-h-[calc(100vh-150px)] bg-[radial-gradient(circle_at_top,rgba(77,20,140,.12),transparent_40%)] flex items-center justify-center px-4 py-12"><div className="w-full max-w-lg rounded-[30px] border border-white bg-white/95 p-7 shadow-[0_30px_90px_rgba(32,45,90,.16)] sm:p-9"><div className="flex justify-center"><button onClick={()=>onNavigate('/')}><Logo/></button></div><div className="mt-7 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#f0e8ff] text-[#4D148C]"><ShieldCheck className="h-7 w-7"/></div><h1 className="mt-4 text-3xl font-black text-[#13255c]">{email?'Your account':mode==='register'?'Create your workspace':'Sign in securely'}</h1><p className="mt-2 text-sm font-semibold leading-6 text-[#6d7a96]">Registered accounts use Google / Gmail through Supabase Auth. Guest shipping stays available without an account.</p></div>{error&&<div className="mt-6 flex gap-2 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-800"><AlertCircle className="h-5 w-5 shrink-0"/>{error}</div>}{email?<div className="mt-7 space-y-3"><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><CheckCircle2 className="mr-2 inline h-5 w-5"/> Signed in as {email}</div><button onClick={finish} className="w-full rounded-2xl bg-[#4D148C] py-3.5 text-sm font-black text-white">Open my dashboard <ArrowRight className="ml-1 inline h-4 w-4"/></button><button onClick={logout} disabled={busy} className="w-full rounded-2xl border border-[#dce3ef] py-3.5 text-sm font-black text-[#2a3a64]"><LogOut className="mr-1 inline h-4 w-4"/> Sign out</button></div>:<div className="mt-7 space-y-4"><button onClick={google} disabled={busy} className="flex w-full items-center justify-center gap-3 rounded-2xl bg-white py-4 text-sm font-black text-[#17285e] shadow-[0_10px_30px_rgba(35,52,94,.12)] ring-1 ring-[#d9e1ed]">{busy?<Loader2 className="h-5 w-5 animate-spin"/>:<span className="grid h-7 w-7 place-items-center rounded-full bg-[#4285F4] text-xs font-black text-white">G</span>} Continue with Google / Gmail</button><button onClick={()=>onNavigate('/guest-shipping')} className="w-full rounded-2xl border border-[#dce3ef] bg-[#fbfcff] py-4 text-sm font-black text-[#2a3a64]">Ship without creating an account <ArrowRight className="ml-1 inline h-4 w-4"/></button></div>}<div className="mt-7 border-t border-[#edf0f5] pt-5 text-center text-[11px] font-semibold text-[#7c879e]">Admin access is role-controlled in the dedicated FedEx Supabase project.</div></div></div>
};