import React, { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, MessageSquare, Paperclip, Send, ShieldCheck } from 'lucide-react';
import { api } from '../lib/api';

interface Props { onNavigate:(path:string)=>void; }

export const CommunicationPage: React.FC<Props> = ({onNavigate}) => {
  const [requestId,setRequestId]=useState('');
  const [email,setEmail]=useState('');
  const [request,setRequest]=useState<any>(null);
  const [message,setMessage]=useState('');
  const [proof,setProof]=useState('');
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const load=async()=>{setError('');setBusy(true);try{setRequest(await api.getGuestRequest(requestId.trim(),email.trim()));}catch(e){setError(e instanceof Error?e.message:'Request not found.')}finally{setBusy(false);}};
  const send=async()=>{if(!message.trim() && !proof.trim())return;setBusy(true);try{await api.sendGuestMessage(requestId.trim(),email.trim(),{message:message.trim(),paymentProofReference:proof.trim()});setMessage('');setProof('');await load();}catch(e){setError(e instanceof Error?e.message:'Message could not be sent.')}finally{setBusy(false);}};
  return <div className="min-h-screen bg-[#f7faff] px-4 py-10"><div className="mx-auto max-w-5xl"><button onClick={()=>onNavigate('/')} className="font-black text-[#4D148C]"><ArrowLeft className="mr-1 inline h-4 w-4"/> Back</button><div className="mt-7 grid gap-5 lg:grid-cols-[.75fr_1.25fr]">
    <div className="rounded-[28px] bg-white p-6 shadow-xl"><MessageSquare className="h-7 w-7 text-[#4D148C]"/><h1 className="mt-4 text-2xl font-black text-[#15275e]">Customer communication</h1><p className="mt-2 text-sm font-semibold leading-6 text-[#71809b]">Use your request number and email to follow payment status, send proof references and contact the operations team.</p><div className="mt-6 space-y-3"><input value={requestId} onChange={e=>setRequestId(e.target.value)} placeholder="Request number / ID" className="w-full rounded-xl border border-[#d9e1ed] px-3 py-3 text-sm font-semibold"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email used for the request" className="w-full rounded-xl border border-[#d9e1ed] px-3 py-3 text-sm font-semibold"/><button disabled={busy} onClick={load} className="w-full rounded-xl bg-[#4D148C] py-3 text-sm font-black text-white">Open communication</button></div>{error&&<div className="mt-4 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{error}</div>}</div>
    <div className="rounded-[28px] bg-white p-6 shadow-xl"><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-[.14em] text-[#4D148C]">Secure thread</div><h2 className="mt-1 text-xl font-black text-[#15275e]">{request?.requestNumber || 'Waiting for request'}</h2></div><ShieldCheck className="h-6 w-6 text-[#18a870]"/></div>{request ? <><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#f6f8fc] p-3"><div className="text-[10px] font-black text-[#7d89a0]">Status</div><div className="mt-1 text-sm font-black text-[#1c2f64]">{request.status}</div></div><div className="rounded-xl bg-[#f6f8fc] p-3"><div className="text-[10px] font-black text-[#7d89a0]">Payment</div><div className="mt-1 text-sm font-black text-[#1c2f64]">{request.paymentStatus || 'Pending'}</div></div></div><div className="mt-5 max-h-[340px] space-y-3 overflow-y-auto rounded-2xl bg-[#f8faff] p-4">{(request.messages||[]).length ? request.messages.map((m:any)=><div key={m.id} className="rounded-xl bg-white p-3 shadow-sm"><div className="flex justify-between text-[10px] font-black text-[#7b879f]"><span>{m.sender}</span><span>{new Date(m.timestamp).toLocaleString()}</span></div><div className="mt-1 text-sm font-semibold text-[#2b3b65]">{m.message}</div>{m.paymentProofReference&&<div className="mt-2 text-xs font-bold text-[#4D148C]">Payment proof reference: {m.paymentProofReference}</div>}</div>) : <div className="py-10 text-center text-sm font-semibold text-[#7b879f]">No messages yet.</div>}</div><div className="mt-4 space-y-2"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a message to operations…" className="min-h-24 w-full rounded-xl border border-[#d9e1ed] px-3 py-3 text-sm font-semibold"/><div className="flex gap-2"><input value={proof} onChange={e=>setProof(e.target.value)} placeholder="Payment proof reference (optional)" className="min-w-0 flex-1 rounded-xl border border-[#d9e1ed] px-3 py-3 text-xs font-semibold"/><button disabled={busy} onClick={send} className="grid h-12 w-12 shrink-0 place-items-center rounded-xl bg-[#4D148C] text-white"><Send className="h-4 w-4"/></button></div><div className="text-[10px] font-semibold text-[#7c879e]"><Paperclip className="mr-1 inline h-3 w-3"/>For security, do not paste card numbers or banking passwords into chat.</div></div></> : <div className="py-24 text-center text-sm font-semibold text-[#7b879f]"><CheckCircle2 className="mx-auto h-8 w-8 text-[#c7d1e2]"/><div className="mt-3">Open a request to see its communication thread.</div></div>}</div>
  </div></div>;
};
